[build]
publish = "public"
command = "yarn link && yarn build:export"

[context.production.environment]
REPOSITORY_URL = "https://github.com/madiedinro/rockstat-web"
CONTEXT = "production"
NODE_VERSION= "8.12.0"
WEBHOOK_TITLE = "rstat.org build"
WEBHOOK_URL = "https://bolt.rstat.org/netlify/build/1"

[[redirects]]
from = "/"
to = "/ru"
status = 303
